# kubectl run db --image mongo
#
# kubectl get pods
#
# docker exec -it k3d-mycluster-server-0 ctr container ls | grep mongo
#
# kubectl delete pod db
#
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    type: db
    vendor: MongoLabs
spec:
  containers:
    - name: db
      image: mongo:6.0.3